<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title></title>
        <script src="/vendors/jquery/dist/jquery.js"></script>
        <script src="/vendors/underscore/underscore.js"></script>
        <script src="/vendors/backbone/backbone.js"></script>
        <script src="/game/game.js"></script>
        <script src="/game/app.js"></script>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>